(()=>{
const world=document.createElement('section');world.id='workWorld';world.className='work-world';world.hidden=true;world.setAttribute('aria-labelledby','workTitle');
const portal=(href,label,cls,scene)=>`<a href="${href}" class="world-portal ${cls}" aria-label="${label}"><span class="portal-scene ${scene}" aria-hidden="true"></span><span class="portal-arc" aria-hidden="true"></span><span class="portal-ground" aria-hidden="true"></span><span class="portal-label">${label}</span></a>`;
world.innerHTML=`<div class="work-backdrop" aria-hidden="true"></div><div class="work-heading"><span class="eyebrow">WORLD / AI & WORK</span><h1 id="workTitle">Research. Products. People.</h1><p>I build AI products, lead technical teams, and turn research into real-world systems.</p></div><div class="work-map"><svg class="work-trail" aria-hidden="true"><path/></svg><span class="work-ball" aria-hidden="true"></span>
<article class="work-card work-ms"><span class="work-orbit" aria-hidden="true"></span><span class="eyebrow">SENIOR APPLIED SCIENTIST</span><h2>Building the next wave of AI.</h2><p>AI agents, language models, and the evaluation that helps us understand them.</p><div class="work-tags"><span>AI agents</span><span>Language models</span><span>Evaluation</span></div></article>
<article class="work-card work-ziva"><span class="eyebrow">HEALTH-TECH STARTUP</span><h2>Head of AI &amp;<br>Product Strategy</h2><span class="work-founding">Founding member</span><p>Led the entire technology function and a team of <strong>15+ engineers</strong>—wearing the AI, engineering, and product strategy hats.</p><div class="work-ownership"><h3>From the ground up</h3><p>Built a connected product ecosystem: Isabella health AI, provider dashboards, patient experience, billing automation, and wearable integrations.</p></div><p class="work-growth">Grew with the startup from 5 to nearly 30 people in 1.5 years.</p></article>
<article class="work-card work-masters"><h2>MS in<br>Data Science</h2><div class="work-columns"><div><h3>Research</h3><p>Exploring machine learning and its real-world applications.</p></div><div><h3>Entrepreneurship</h3><p>Bringing a builder’s perspective to research and ideas.</p></div></div></article>
<article class="work-card work-small work-mba"><span class="eyebrow">UC SAN DIEGO · RADY</span><h2>MicroMBA</h2><p>A business perspective.</p></article>
<article class="work-card work-small work-ige"><span class="eyebrow">UC SAN DIEGO</span><h2>IGE</h2><p>Innovation & entrepreneurship.</p></article>
<article class="work-card work-small work-startr"><span class="eyebrow">StartR Accelerator</span><h2>Ideas into a venture.</h2><p>StartR Demo Day winner.</p></article>
<article class="work-card work-lime"><img class="work-company-logo work-logo-lime" src="assets/brands/lime.svg" alt="Lime"><span class="eyebrow">DATA SCIENCE SUMMER ASSOCIATE · RIDER TEAM</span><h2>Getting riders help.</h2><p>Built an LLM-powered risk reduction framework that helped prioritize urgent rider tickets.</p><p class="work-lime-detail">Partnered with three customer-facing product teams to turn rider feedback into insights for product decisions.</p><div class="work-tags"><span>Rider experience</span><span>LLMs</span><span>Product insights</span></div></article>
<article class="work-card work-asr"><span class="eyebrow">DATA SCIENTIST · OPEN-SOURCE ASR</span><h2>India’s first-ever, largest<br>open-source ASR system.</h2><span class="metric">23</span><span class="metric-note">Indian languages · Project Vakyansh</span><p>Built speech recognition technology adopted by the government.</p><div class="work-wave" aria-hidden="true">${Array.from({length:40},(_,i)=>`<i style="--h:${10+Math.sin(i*.7)**2*40}px;--d:${-i*.13}s"></i>`).join('')}</div><div class="work-tags"><span>Speech recognition</span><span>Open source</span></div></article></div><div class="work-end">${portal('#world','World','portal-back','portal-world')}${portal('#speaking','Speaking','portal-next','portal-speaking')}</div>`;
document.body.append(world);
const logoFilter=document.createElementNS('http://www.w3.org/2000/svg','svg');logoFilter.setAttribute('width','0');logoFilter.setAttribute('height','0');logoFilter.setAttribute('aria-hidden','true');logoFilter.style.position='absolute';logoFilter.innerHTML='<defs><filter id="work-logo-knockout" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  -1 -1 -1 0 3"/><feComposite in2="SourceGraphic" operator="in"/></filter></defs>';world.append(logoFilter);
const whiteFilter=document.createElementNS('http://www.w3.org/2000/svg','svg');whiteFilter.setAttribute('width','0');whiteFilter.setAttribute('height','0');whiteFilter.style.position='absolute';whiteFilter.setAttribute('aria-hidden','true');whiteFilter.innerHTML='<defs><filter id="work-logo-white" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 -1 -1 -1 0 3"/><feComposite in2="SourceGraphic" operator="in"/></filter></defs>';world.append(whiteFilter);
const brands={ms:['microsoft.jpg','Microsoft'],ziva:['ziva.png','Ziva Health'],masters:['ucsd.png','UC San Diego'],asr:['thoughtworks.svg','Thoughtworks']};
for(const [key,[file,name]] of Object.entries(brands)){const logo=document.createElement('img');logo.className='work-company-logo work-logo-'+key;logo.src='assets/brands/'+file;logo.alt=name;world.querySelector('.work-'+key).prepend(logo)}
const zivaLogo=world.querySelector('.work-logo-ziva');const zivaWrap=document.createElement('span');zivaWrap.className='work-ziva-brand';zivaLogo.replaceWith(zivaWrap);zivaWrap.append(zivaLogo);const zivaWhite=zivaLogo.cloneNode();zivaWhite.classList.add('ziva-white-word');zivaWhite.alt='';zivaWhite.setAttribute('aria-hidden','true');zivaWrap.append(zivaWhite);
const qualities=document.createElement('section');qualities.className='work-qualities';qualities.setAttribute('aria-label','Research, AI, Product, Entrepreneurship');
qualities.innerHTML=`<p class="qualities-intro">Four perspectives. One way of building.</p><div class="quality-constellation"><svg class="quality-links" viewBox="0 0 640 420" preserveAspectRatio="none" aria-hidden="true"><path d="M320 210 Q180 210 150 90 M320 210 Q450 210 490 90 M320 210 Q180 210 150 335 M320 210 Q450 210 490 335"/><ellipse cx="320" cy="210" rx="200" ry="136"/></svg><div class="quality-heart"><span class="quality-heart-spark" aria-hidden="true">✧</span><strong>Ideas into<br>real-world impact.</strong><span>My connecting thread</span></div><div class="quality-node quality-research"><span class="quality-symbol" aria-hidden="true">⌕</span><strong>Research</strong><span>Ask better questions.</span></div><div class="quality-node quality-ai"><span class="quality-symbol" aria-hidden="true">✧</span><strong>AI</strong><span>Build with depth.</span></div><div class="quality-node quality-product"><span class="quality-symbol" aria-hidden="true">◇</span><strong>Product</strong><span>Make it matter.</span></div><div class="quality-node quality-founder"><span class="quality-symbol" aria-hidden="true">↗</span><strong>Entrepreneurship</strong><span>Take it from zero to one.</span></div><span class="quality-traveller" aria-hidden="true"></span></div>`;
world.querySelector('.work-end').before(qualities);
const map=world.querySelector('.work-map'),path=world.querySelector('path'),ball=world.querySelector('.work-ball'),cards=[...world.querySelectorAll('.work-card')],reduce=matchMedia('(prefers-reduced-motion: reduce)');let length=0,frame=0,pos=0,target=0,lastSpark=0;
let lastTime=0;
function layout(){
 if(world.hidden)return;
 world.style.setProperty('--world-height',world.scrollHeight+'px');
 // Route through the cards themselves; changes in direction are concealed beneath them.
 const stops=cards.map(card=>({x:card.offsetLeft+card.offsetWidth*.5,y:card.offsetTop+card.offsetHeight*.64})).sort((a,b)=>a.y-b.y);
 let d=`M ${stops[0].x} ${stops[0].y}`;
 for(let i=1;i<stops.length;i++){const a=stops[i-1],b=stops[i],dx=b.x-a.x,reach=Math.abs(dx)*.48;const direction=dx>=0?1:-1;d+=` C ${a.x+direction*reach} ${a.y}, ${b.x-direction*reach} ${b.y}, ${b.x} ${b.y}`;}
 path.setAttribute('d',d);length=path.getTotalLength();map.querySelector('.work-branches')?.remove();update();
}
function update(){const view=world.clientHeight;cards.forEach(card=>{const top=map.offsetTop+card.offsetTop-world.scrollTop;const depth=reduce.matches?0:Math.max(0,Math.min(1,(view*.28-top)/view));card.style.setProperty('--recede-scale',1-depth*.18);card.style.setProperty('--recede-y',(-depth*35)+'px')});world.style.setProperty('--water-scale',reduce.matches?1:1.06-Math.min(.06,world.scrollTop/Math.max(1,world.scrollHeight-view)*.06));document.body.classList.toggle('work-scrolled',!world.hidden&&world.scrollTop>50);const y=Math.max(0,Math.min(map.clientHeight,world.scrollTop+world.clientHeight*.58-map.offsetTop));let lo=0,hi=length;for(let i=0;i<18;i++){const mid=(lo+hi)/2;if(path.getPointAtLength(mid).y<y)lo=mid;else hi=mid}target=(lo+hi)/2;if(!frame&&!reduce.matches&&!world.hidden){lastTime=0;frame=requestAnimationFrame(tick)}}
function tick(time){frame=0;if(world.hidden||reduce.matches)return;const dt=lastTime?Math.min(time-lastTime,40):16;lastTime=time;const delta=(target-pos)*(1-Math.exp(-dt/260));pos+=Math.max(-dt*.85,Math.min(dt*.85,delta));const p=path.getPointAtLength(pos);ball.style.transform=`translate(${p.x-8}px,${p.y-8}px)`;if(Math.abs(target-pos)>.1)frame=requestAnimationFrame(tick)}
world.addEventListener('scroll',update,{passive:true});new ResizeObserver(layout).observe(map);
world.addEventListener('pointermove',e=>{if(reduce.matches||e.pointerType!=='mouse')return;const card=e.target.closest('.work-card');if(card){const r=card.getBoundingClientRect();card.style.setProperty('--mx',`${e.clientX-r.left}px`);card.style.setProperty('--my',`${e.clientY-r.top}px`)}const now=performance.now();if(now-lastSpark<85)return;lastSpark=now;const spark=document.createElement('i');spark.className='work-spark';spark.style.left=e.clientX+'px';spark.style.top=e.clientY+world.scrollTop+'px';world.append(spark);spark.addEventListener('animationend',()=>spark.remove(),{once:true})});
function sync(){const active=['#work/journey','#journey'].includes(location.hash);world.hidden=!active;document.body.classList.remove('work-scrolled');if(active){pauseTour();world.scrollTop=0;requestAnimationFrame(layout)}else{cancelAnimationFrame(frame);frame=0}}
addEventListener('hashchange',sync);reduce.addEventListener('change',()=>{cancelAnimationFrame(frame);frame=0;update()});sync();
})();
